### ISSUE TITLE
Question about dataset BC40

### ISSUE THREAD

**Issue by linbc-73** [MattMcPartlon/AttnPacker#8]
Hi I am very interested in side chain packing problem. However I encountered some problem when I tried to download the BC40 dataset. I found this link https://drug.ai.tencent.com/protein/bc40/download.html in AttnPacker paper, from which I downloaded two zip files called bc40_ss3.tar.gz and bc40_label.tar.gz. I am not sure what the files within these 2 zip files mean as the website provides little explanation. So I am hoping maybe you can help me. Thanks in advance!
Specifically, in the zip file bc40_label.tar.gz, there are 36,929 .label files, such as 1a0aA.label. Do you know waht 1a0aA stand for? I thought it's the id of a protein but I couldn't find it in PDB. And also what is the relationship between these data and those 39k proteins used for training in AttnPacker? And how can I find the pdb files for those 39k proteins?

**Comment by MattMcPartlon** [comment]
discussed over email - closing
