### ISSUE TITLE
Weight models files

### ISSUE THREAD

**Issue by ibalafkir** [MattMcPartlon/AttnPacker#9]
Hi!

In the "models" directory of the weights, there are three .tar files: "fbb_design_21_12_2022_15:57:43.tar", "fbb_design_21_12_2022_16:00:06.tar", and "fbb_design_21_12_2022_16:07:51.tar". I am curious about the differences between these files. By decompressing only the first one, inference procedures work without any problems.

**Comment by MattMcPartlon** [comment]
Sorry for the confusion. the models were trained differently and have slightly different functinoality (see below). If you pass the respective kwargs to the inference module it will select the appropriate model (i.e. something along the lines of `use_rotamer_conditioning` or `use_design_variant`).

    "fbb_design_21_12_2022_15:57:43"  # baseline SCP model
    "fbb_design_21_12_2022_16:07:51"   # SCP + sequence design
    "fbb_design_05_04_2023_17:56:52" # SCP + sequence design + rotamer conditioning
    "fbb_design_05_04_2023_17:56:21"  # sequence design + rotamer conditioning + trained with gaussian noise sigma=0.05

**Comment by ibalafkir** [comment]
Thanks for the info :)
